# Generated by Django 5.1.5 on 2025-02-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.IntegerField()),
                ('roleGenID', models.CharField(max_length=255)),
                ('roleName', models.CharField(max_length=255)),
                ('roleDescription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
